name: Build

on: ['push', 'pull_request']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: falti/dotenv-action@v0.2.4
      - run: >
          docker build .
          --build-arg ALPINE_VERSION=$ALPINE_VERSION
          --build-arg COMPOSER_VERSION=$COMPOSER_VERSION
