name: Build

on: ['push', 'pull_request']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: dotenv
        uses: falti/dotenv-action@v0.2.4
      - uses: elgohr/Publish-Docker-Github-Action@2.16
        with:
          name: ${{ steps.dotenv.outputs.IMAGE_NAME }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          buildoptions: >
            --build-arg ALPINE_VERSION=${{ steps.dotenv.outputs.ALPINE_VERSION }}
            --build-arg COMPOSER_VERSION=${{ steps.dotenv.outputs.COMPOSER_VERSION }}